# Generated by Django 5.0.2 on 2024-04-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
