# Generated by Django 5.0.2 on 2024-03-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_order_email_remove_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='zip_code',
        ),
    ]
