# Generated by Django 5.0.2 on 2024-03-25 07:23

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_shipments_state_remove_shipments_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, length=15, max_length=20, prefix='banner', primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.packages')),
            ],
        ),
    ]
