# Generated by Django 5.0.2 on 2024-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='titile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
