# Generated by Django 5.0.2 on 2024-03-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_banner_titile'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rated_package', to='base.review'),
        ),
    ]
