# Generated by Django 5.0.2 on 2024-03-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_shipments_cart_shipments_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='shipped',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('NOT_SHIPPED', 'Not Shipped')], default='NOT_SHIPPED', max_length=12),
        ),
    ]
