# Generated by Django 5.0.2 on 2024-03-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_shipments_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipments',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('NOT_SHIPPED', 'Not Shipped')], default='NOT_SHIPPED', max_length=12),
        ),
    ]
