# Generated by Django 5.0.2 on 2024-03-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_supermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supermodel',
            name='products',
        ),
    ]
