# Generated by Django 5.0.2 on 2024-04-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_supermodel_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='address',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='shipments',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='hair_type',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='height',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='skin_type',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='snapchat',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='supermodel',
            name='youtube',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
