# Generated by Django 5.0.2 on 2024-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_address_shipments_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
