# Generated by Django 5.0.2 on 2024-04-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_supermodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperModel',
        ),
    ]
