# Generated by Django 5.0.2 on 2024-04-06 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_delete_supermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperModel',
            fields=[
                ('user_name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('instagram', models.CharField(max_length=100)),
                ('tiktok', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
